name: yqnancy
favicon: null
layout_spectrum: 0.44618294574320316
typography_spectrum: 0.28524126508273184
title: No Name
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a706e'
    - '#ccdadb'
    - '#42423a'
    - '#ffffff'
    - '#171b1c'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.374438971048221
  rhythmicContrast: 0.25
purpose: []
